apiVersion: v1
kind: Service
metadata:
  name: java-web01
  namespace: default
spec:
  type: NodePort
  selector:
    app: java-web01
  ports:
  - name: http
    nodePort: 31602
    port: 8888
    targetPort: 8888
